using Prism.Navigation;
using ReactiveUI;
using ReactiveUI.Fody.Helpers;
using System;
using System.Collections.Generic;
using System.Reactive.Disposables;
using System.Threading;
using System.Threading.Tasks;
using Template.Mobile.Models;
using Xamarin.Essentials;
using Xamarin.Forms;

namespace Template.Mobile.ViewModels
{
    public class Debug_ImagesViewModel : ViewModelBase
    {
        public Debug_ImagesViewModel(INavigationService navigationService) : base(navigationService)
        {
            this.WhenAnyValue(x => x.SelectedIcon_Generic).Subscribe(ShowImage).DisposeWith(DestroyWith);
            this.WhenAnyValue(x => x.SelectedIcon_Material).Subscribe(ShowImage).DisposeWith(DestroyWith);
        }

        #region Services


        #endregion

        #region Properties

        public List<ImageModel> ListIcons_Generic { get; private set; } = new List<ImageModel>();
        public List<ImageModel> ListIcons_Material { get; private set; } = new List<ImageModel>();

        [Reactive]
        public ImageModel SelectedIcon_Generic { get; set; }

        [Reactive]
        public ImageModel SelectedIcon_Material { get; set; }

        [Reactive]
        public int AdjustableGridColumnNumber { get; set; } = 3;

        #endregion

        #region Commands

        #endregion

        #region Methods

        private void LoadDatas()
        {
            //Icons are renderer in native PNG !!! (source is SVG in shared)
            //Generic Projects Images
            ListIcons_Generic.AddRange( new[] {
                new ImageModel(){ Filename="appicon.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="splash_centered.png", ImageHeight=19, ImageWidth=48},
                new ImageModel(){ Filename="splash_background.png", ImageHeight=128, ImageWidth=72},
                new ImageModel(){ Filename="background_blur.png", ImageHeight=128, ImageWidth=72},
                new ImageModel(){ Filename="background_darkblur.png", ImageHeight=128, ImageWidth=72},
                new ImageModel(){ Filename="menu_background_dark.png", ImageHeight=41, ImageWidth=72},
                new ImageModel(){ Filename="menu_background_light.png", ImageHeight=41, ImageWidth=72},
                new ImageModel(){ Filename="ic_menu.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_exit_to_app.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_add.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_image.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_brightness_6.png", ImageHeight=48, ImageWidth=48},
                }
            );
            //Materials Icons
            ListIcons_Material.AddRange(new[] {
                new ImageModel(){ Filename="ic_3d_rotation.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_accessibility.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_accessible.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_access_alarm.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_access_alarms.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_access_time.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_account_balance.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_account_balance_wallet.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_account_box.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_account_circle.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_ac_unit.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_adb.png", ImageHeight=48, ImageWidth=48},
                //new ImageModel(){ Filename="ic_add.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_add_alarm.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_add_alert.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_add_a_photo.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_add_box.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_add_circle.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_add_circle_outline.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_add_location.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_add_shopping_cart.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_add_to_photos.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_add_to_queue.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_adjust.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_airline_seat_flat.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_airline_seat_flat_angled.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_airline_seat_individual_suite.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_airline_seat_legroom_extra.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_airline_seat_legroom_normal.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_airline_seat_legroom_reduced.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_airline_seat_recline_extra.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_airline_seat_recline_normal.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_airplanemode_active.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_airplanemode_inactive.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_airplay.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_airport_shuttle.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_alarm.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_alarm_add.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_alarm_off.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_alarm_on.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_album.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_all_inclusive.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_all_out.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_android.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_announcement.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_apps.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_archive.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_arrow_back.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_arrow_downward.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_arrow_drop_down.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_arrow_drop_down_circle.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_arrow_drop_up.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_arrow_forward.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_arrow_upward.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_art_track.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_aspect_ratio.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_assessment.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_assignment.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_assignment_ind.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_assignment_late.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_assignment_return.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_assignment_returned.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_assignment_turned_in.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_assistant.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_assistant_photo.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_attachment.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_attach_file.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_attach_money.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_audiotrack.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_autorenew.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_av_timer.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_backspace.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_backup.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_battery_20.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_battery_30.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_battery_50.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_battery_60.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_battery_80.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_battery_90.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_battery_alert.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_battery_charging_20.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_battery_charging_30.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_battery_charging_50.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_battery_charging_60.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_battery_charging_80.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_battery_charging_90.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_battery_charging_full.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_battery_full.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_battery_std.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_battery_unknown.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_beach_access.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_beenhere.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_block.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_bluetooth.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_bluetooth_audio.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_bluetooth_connected.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_bluetooth_disabled.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_bluetooth_searching.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_blur_circular.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_blur_linear.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_blur_off.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_blur_on.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_book.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_bookmark.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_bookmark_border.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_border_all.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_border_bottom.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_border_clear.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_border_color.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_border_horizontal.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_border_inner.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_border_left.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_border_outer.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_border_right.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_border_style.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_border_top.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_border_vertical.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_branding_watermark.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_brightness_1.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_brightness_2.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_brightness_3.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_brightness_4.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_brightness_5.png", ImageHeight=48, ImageWidth=48},
                //new ImageModel(){ Filename="ic_brightness_6.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_brightness_7.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_brightness_auto.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_brightness_high.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_brightness_low.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_brightness_medium.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_broken_image.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_brush.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_bubble_chart.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_bug_report.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_build.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_burst_mode.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_business.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_business_center.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_cached.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_cake.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_call.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_call_end.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_call_made.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_call_merge.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_call_missed.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_call_missed_outgoing.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_call_received.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_call_split.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_call_to_action.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_camera.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_camera_alt.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_camera_front.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_camera_rear.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_camera_roll.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_cancel.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_card_giftcard.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_card_membership.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_card_travel.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_casino.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_cast.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_cast_connected.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_center_focus_strong.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_center_focus_weak.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_change_history.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_chat.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_chat_bubble.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_chat_bubble_outline.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_check.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_check_box.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_check_box_outline_blank.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_check_circle.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_chevron_left.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_chevron_right.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_child_care.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_child_friendly.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_chrome_reader_mode.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_class.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_clear.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_clear_all.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_close.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_closed_caption.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_cloud.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_cloud_circle.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_cloud_done.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_cloud_download.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_cloud_off.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_cloud_queue.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_cloud_upload.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_code.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_collections.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_colorize.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_color_lens.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_comment.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_compare.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_compare_arrows.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_computer.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_confirmation_number.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_contacts.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_contact_mail.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_contact_phone.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_content_copy.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_content_cut.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_content_paste.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_control_point.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_control_point_duplicate.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_copyright.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_create.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_create_new_folder.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_credit_card.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_crop.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_crop_16_9.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_crop_3_2.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_crop_5_4.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_crop_7_5.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_crop_din.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_crop_free.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_crop_landscape.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_crop_original.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_crop_portrait.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_crop_rotate.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_crop_square.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_dashboard.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_data_usage.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_date_range.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_dehaze.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_delete.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_delete_forever.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_delete_sweep.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_description.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_desktop_mac.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_desktop_windows.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_details.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_developer_board.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_developer_mode.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_devices.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_devices_other.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_dialer_sip.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_dialpad.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_directions.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_directions_bike.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_directions_boat.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_directions_bus.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_directions_car.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_directions_railway.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_directions_run.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_directions_subway.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_directions_transit.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_directions_walk.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_disc_full.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_dns.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_dock.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_domain.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_done.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_done_all.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_donut_large.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_donut_small.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_do_not_disturb.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_do_not_disturb_alt.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_do_not_disturb_off.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_do_not_disturb_on.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_drafts.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_drag_handle.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_drive_eta.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_dvr.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_edit.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_edit_location.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_email.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_enhanced_encryption.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_equalizer.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_error.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_error_outline.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_euro_symbol.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_event.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_event_available.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_event_busy.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_event_note.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_event_seat.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_ev_station.png", ImageHeight=48, ImageWidth=48},
                //new ImageModel(){ Filename="ic_exit_to_app.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_expand_less.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_expand_more.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_explicit.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_explore.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_exposure.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_exposure_neg_1.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_exposure_neg_2.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_exposure_plus_1.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_exposure_plus_2.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_exposure_zero.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_extension.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_face.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_fast_forward.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_fast_rewind.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_favorite.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_favorite_border.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_featured_play_list.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_featured_video.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_feedback.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_fiber_dvr.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_fiber_manual_record.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_fiber_new.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_fiber_pin.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_fiber_smart_record.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_file_download.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_file_upload.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_filter.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_filter_1.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_filter_2.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_filter_3.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_filter_4.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_filter_5.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_filter_6.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_filter_7.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_filter_8.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_filter_9.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_filter_9_plus.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_filter_b_and_w.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_filter_center_focus.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_filter_drama.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_filter_frames.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_filter_hdr.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_filter_list.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_filter_none.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_filter_tilt_shift.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_filter_vintage.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_find_in_page.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_find_replace.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_fingerprint.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_first_page.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_fitness_center.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_flag.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_flare.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_flash_auto.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_flash_off.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_flash_on.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_flight.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_flight_land.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_flight_takeoff.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_flip.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_flip_to_back.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_flip_to_front.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_folder.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_folder_open.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_folder_shared.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_folder_special.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_format_align_center.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_format_align_justify.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_format_align_left.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_format_align_right.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_format_bold.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_format_clear.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_format_color_fill.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_format_color_reset.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_format_color_text.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_format_indent_decrease.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_format_indent_increase.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_format_italic.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_format_line_spacing.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_format_list_bulleted.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_format_list_numbered.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_format_paint.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_format_quote.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_format_shapes.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_format_size.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_format_strikethrough.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_format_textdirection_l_to_r.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_format_textdirection_r_to_l.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_format_underlined.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_forum.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_forward.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_forward_10.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_forward_30.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_forward_5.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_free_breakfast.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_fullscreen.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_fullscreen_exit.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_functions.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_gamepad.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_games.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_gavel.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_gesture.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_get_app.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_golf_course.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_gps_fixed.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_gps_not_fixed.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_gps_off.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_grade.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_gradient.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_grain.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_graphic_eq.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_grid_off.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_grid_on.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_group.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_group_add.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_group_work.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_g_translate.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_hdr_off.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_hdr_on.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_hdr_strong.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_hdr_weak.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_headset.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_headset_mic.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_healing.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_hearing.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_help.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_highlight.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_highlight_off.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_high_quality.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_history.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_home.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_hotel.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_hot_tub.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_hourglass_empty.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_hourglass_full.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_http.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_https.png", ImageHeight=48, ImageWidth=48},
                //new ImageModel(){ Filename="ic_image.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_image_aspect_ratio.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_important_devices.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_import_contacts.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_import_export.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_inbox.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_info.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_info_outline.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_input.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_insert_chart.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_insert_comment.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_insert_drive_file.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_insert_emoticon.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_insert_invitation.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_insert_link.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_insert_photo.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_invert_colors.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_invert_colors_off.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_iso.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_keyboard.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_keyboard_arrow_down.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_keyboard_arrow_left.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_keyboard_arrow_right.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_keyboard_arrow_up.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_keyboard_backspace.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_keyboard_capslock.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_keyboard_hide.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_keyboard_return.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_keyboard_tab.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_keyboard_voice.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_kitchen.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_label.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_label_outline.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_landscape.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_language.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_laptop.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_laptop_chromebook.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_laptop_mac.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_laptop_windows.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_last_page.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_launch.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_layers.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_layers_clear.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_leak_add.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_leak_remove.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_lens.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_library_add.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_library_books.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_library_music.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_lightbulb_outline.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_linear_scale.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_line_style.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_line_weight.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_link.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_linked_camera.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_list.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_live_help.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_live_tv.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_activity.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_airport.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_atm.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_bar.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_cafe.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_car_wash.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_convenience_store.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_dining.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_drink.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_florist.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_gas_station.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_grocery_store.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_hospital.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_hotel.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_laundry_service.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_library.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_mall.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_movies.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_offer.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_parking.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_pharmacy.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_phone.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_pizza.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_play.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_post_office.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_printshop.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_see.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_shipping.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_local_taxi.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_location_city.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_location_disabled.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_location_off.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_location_on.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_location_searching.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_lock.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_lock_open.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_lock_outline.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_looks.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_looks_3.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_looks_4.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_looks_5.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_looks_6.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_looks_one.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_looks_two.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_loop.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_loupe.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_low_priority.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_loyalty.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_mail.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_mail_outline.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_map.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_markunread.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_markunread_mailbox.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_memory.png", ImageHeight=48, ImageWidth=48},
                //new ImageModel(){ Filename="ic_menu.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_merge_type.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_message.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_mic.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_mic_none.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_mic_off.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_mms.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_mode_comment.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_mode_edit.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_monetization_on.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_monochrome_photos.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_mood.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_mood_bad.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_more.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_more_horiz.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_more_vert.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_motorcycle.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_mouse.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_move_to_inbox.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_movie.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_movie_creation.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_movie_filter.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_multiline_chart.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_music_note.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_music_video.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_my_location.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_nature.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_nature_people.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_navigate_before.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_navigate_next.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_navigation.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_near_me.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_network_cell.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_network_check.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_network_locked.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_network_wifi.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_new_releases.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_next_week.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_nfc.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_note.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_note_add.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_notifications.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_notifications_active.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_notifications_none.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_notifications_off.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_notifications_paused.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_not_interested.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_no_encryption.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_no_sim.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_ondemand_video.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_opacity.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_open_in_browser.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_open_in_new.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_open_with.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_pages.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_pageview.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_palette.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_panorama.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_panorama_fish_eye.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_panorama_horizontal.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_panorama_vertical.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_panorama_wide_angle.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_pan_tool.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_party_mode.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_pause.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_pause_circle_filled.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_pause_circle_outline.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_payment.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_people.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_people_outline.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_perm_camera_mic.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_perm_contact_calendar.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_perm_data_setting.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_perm_device_information.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_perm_identity.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_perm_media.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_perm_phone_msg.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_perm_scan_wifi.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_person.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_personal_video.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_person_add.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_person_outline.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_person_pin.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_person_pin_circle.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_pets.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_phone.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_phonelink.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_phonelink_off.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_phone_android.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_phone_bluetooth_speaker.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_phone_forwarded.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_phone_in_talk.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_phone_iphone.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_phone_locked.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_phone_missed.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_phone_paused.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_photo.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_photo_album.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_photo_camera.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_photo_filter.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_photo_library.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_picture_as_pdf.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_picture_in_picture.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_picture_in_picture_alt.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_pie_chart.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_pie_chart_outlined.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_pin_drop.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_place.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_playlist_add.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_playlist_add_check.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_playlist_play.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_play_arrow.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_play_circle_filled.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_play_circle_filled_white.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_play_circle_outline.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_play_for_work.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_plus_one.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_poll.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_polymer.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_pool.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_portable_wifi_off.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_portrait.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_power.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_power_input.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_power_settings_new.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_pregnant_woman.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_present_to_all.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_print.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_priority_high.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_priority_high_12px.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_public.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_publish.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_query_builder.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_question_answer.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_queue.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_queue_music.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_queue_play_next.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_radio.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_radio_button_checked.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_radio_button_unchecked.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_rate_review.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_receipt.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_recent_actors.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_record_voice_over.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_redeem.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_redo.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_refresh.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_remove.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_remove_circle.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_remove_circle_outline.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_remove_from_queue.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_remove_red_eye.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_remove_shopping_cart.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_repeat.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_repeat_one.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_replay.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_replay_10.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_replay_30.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_replay_5.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_reply.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_reply_all.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_report.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_report_problem.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_restaurant.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_restaurant_menu.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_restore.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_restore_page.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_ring_volume.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_room.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_room_service.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_rotate_90_degrees_ccw.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_rotate_left.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_rotate_right.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_rounded_corner.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_router.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_rowing.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_rss_feed.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_rv_hookup.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_satellite.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_save.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_scanner.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_schedule.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_school.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_screen_lock_landscape.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_screen_lock_portrait.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_screen_lock_rotation.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_screen_rotation.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_screen_share.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_sd_card.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_sd_storage.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_search.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_security.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_select_all.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_send.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_sentiment_dissatisfied.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_sentiment_neutral.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_sentiment_satisfied.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_sentiment_very_dissatisfied.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_sentiment_very_satisfied.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_settings.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_settings_applications.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_settings_backup_restore.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_settings_bluetooth.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_settings_brightness.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_settings_cell.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_settings_ethernet.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_settings_input_antenna.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_settings_input_component.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_settings_input_composite.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_settings_input_hdmi.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_settings_input_svideo.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_settings_overscan.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_settings_phone.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_settings_power.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_settings_remote.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_settings_system_daydream.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_settings_voice.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_share.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_shop.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_shopping_basket.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_shopping_cart.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_shop_two.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_short_text.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_show_chart.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_shuffle.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_cellular_0_bar.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_cellular_1_bar.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_cellular_2_bar.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_cellular_3_bar.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_cellular_4_bar.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_cellular_connected_no_internet_0_bar.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_cellular_connected_no_internet_1_bar.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_cellular_connected_no_internet_2_bar.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_cellular_connected_no_internet_3_bar.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_cellular_connected_no_internet_4_bar.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_cellular_no_sim.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_cellular_null.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_cellular_off.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_wifi_0_bar.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_wifi_1_bar.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_wifi_1_bar_lock.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_wifi_2_bar.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_wifi_2_bar_lock.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_wifi_3_bar.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_wifi_3_bar_lock.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_wifi_4_bar.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_wifi_4_bar_lock.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_wifi_off.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_wifi_statusbar_1_bar_26x24px.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_wifi_statusbar_2_bar_26x24px.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_wifi_statusbar_3_bar_26x24px.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_wifi_statusbar_4_bar_26x24px.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_wifi_statusbar_connected_no_internet_1_26x24px.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_wifi_statusbar_connected_no_internet_26x24px.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_wifi_statusbar_connected_no_internet_2_26x24px.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_wifi_statusbar_connected_no_internet_3_26x24px.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_wifi_statusbar_connected_no_internet_4_26x24px.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_wifi_statusbar_not_connected_26x24px.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_signal_wifi_statusbar_null_26x24px.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_sim_card.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_sim_card_alert.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_skip_next.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_skip_previous.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_slideshow.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_slow_motion_video.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_smartphone.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_smoke_free.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_smoking_rooms.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_sms.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_sms_failed.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_snooze.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_sort.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_spa.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_space_bar.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_speaker.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_speaker_group.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_speaker_notes.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_speaker_notes_off.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_speaker_phone.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_spellcheck.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_stars.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_star_half.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_stay_current_landscape.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_stay_current_portrait.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_stay_primary_landscape.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_stay_primary_portrait.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_stop.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_stop_screen_share.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_storage.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_store.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_store_mall_directory.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_straighten.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_streetview.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_strikethrough_s.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_style.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_subdirectory_arrow_left.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_subdirectory_arrow_right.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_subject.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_subscriptions.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_subtitles.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_subway.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_supervisor_account.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_surround_sound.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_swap_calls.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_swap_horiz.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_swap_vert.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_swap_vertical_circle.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_switch_camera.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_switch_video.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_sync.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_sync_disabled.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_sync_problem.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_system_update.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_system_update_alt.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_tab.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_tablet.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_tablet_android.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_tablet_mac.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_tab_unselected.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_tag_faces.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_tap_and_play.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_terrain.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_textsms.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_texture.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_text_fields.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_text_format.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_theaters.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_thumbs_up_down.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_thumb_down.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_thumb_up.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_timelapse.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_timeline.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_timer.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_timer_10.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_timer_3.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_timer_off.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_time_to_leave.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_title.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_toc.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_today.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_toll.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_tonality.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_touch_app.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_toys.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_track_changes.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_traffic.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_train.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_tram.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_transfer_within_a_station.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_transform.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_translate.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_trending_down.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_trending_flat.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_trending_up.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_tune.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_turned_in.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_turned_in_not.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_tv.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_unarchive.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_undo.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_unfold_less.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_unfold_more.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_update.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_usb.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_verified_user.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_vertical_align_bottom.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_vertical_align_center.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_vertical_align_top.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_vibration.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_videocam.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_videocam_off.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_videogame_asset.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_video_call.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_video_label.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_video_library.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_view_agenda.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_view_array.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_view_carousel.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_view_column.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_view_comfy.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_view_compact.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_view_day.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_view_headline.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_view_list.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_view_module.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_view_quilt.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_view_stream.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_view_week.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_visibility.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_visibility_off.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_voicemail.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_voice_chat.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_volume_down.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_volume_mute.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_volume_off.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_volume_up.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_vpn_key.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_vpn_lock.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_wallpaper.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_warning.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_watch.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_watch_later.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_wb_auto.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_wb_cloudy.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_wb_incandescent.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_wb_iridescent.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_wb_sunny.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_wc.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_web.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_web_asset.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_weekend.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_whatshot.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_widgets.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_wifi.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_wifi_lock.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_wifi_tethering.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_work.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_wrap_text.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_youtube_searched_for.png", ImageHeight=48, ImageWidth=48},
                new ImageModel(){ Filename="ic_zoom_out_map.png" , ImageHeight=48, ImageWidth=48}
                }
            );
        }

        public void RefreshColumnNumber()
        {
            Device.BeginInvokeOnMainThread(() =>
            {
                if (Device.Idiom == TargetIdiom.Phone)
                {
                    //Phone
                    if (DeviceDisplay.MainDisplayInfo.Orientation == DisplayOrientation.Portrait)
                    {
                        //Portrait
                        AdjustableGridColumnNumber = 3;
                    }
                    else
                    {
                        //Landscape
                        AdjustableGridColumnNumber = 4;
                    }
                }
                else
                {
                    //Not on a phone (tablet/pc/etc.)
                    if (DeviceDisplay.MainDisplayInfo.Orientation == DisplayOrientation.Portrait)
                    {
                        //Portrait
                        AdjustableGridColumnNumber = 4;
                    }
                    else
                    {
                        //Landscape
                        AdjustableGridColumnNumber = 5;
                    }
                }
            });
        }

        private void ShowImage(ImageModel image)
        {
            Console.WriteLine($"#################################################");
            Console.WriteLine($"Filename : {image?.Filename}");
            Console.WriteLine($"#################################################");
        }

        #endregion

        #region LifeCycle

        public override void Initialize(INavigationParameters parameters)
        {
            base.Initialize(parameters);
            Task.Run(() => LoadDatas());
            //Fake long loading for LazyView Test
            Task.Delay(5000);
        }

        public override void OnAppearing()
        {
            base.OnAppearing();
            Task.Run(() => RefreshColumnNumber());
        }

        #endregion

    }

}
